### ISSUE TITLE
Anti-pattern: HTTP Without TLS

### ISSUE THREAD

**Issue by akondasif** [oktadev/jhipster-microservices-example#47]
Dear Colleague,

We are looking to find ways to help developers find security anti-patterns, i.e., violation of security best practices in Kubernetes manifests.

We have noticed an instance of HTTP without TLS/SSL in one of your Kubernetes manifests. The recommended practice is use of secure HTTP for each team's development and production environment. Enabling TLS ensures secure communication between cluster components.. For examples of Kubernetes security anti-patterns we are following our peer-reviewed publication on Kubernetes security best practices (https://arxiv.org/pdf/2006.15275.pdf).

Location of security anti-pattern:

https://github.com/oktadev/jhipster-microservices-example/blob/5e4631f402be50585fbb36e2776c5b6e733253f4/kubernetes/registry/application-configmap.yml#L16

**Comment by mraible** [comment]
Thanks, but this is an internal call so I'm not too worried. This is also an old example. It's been around for over four years, which is ancient in internet time. See [Secure Service-to-Service Spring Microservices with HTTPS and OAuth 2.0](https://developer.okta.com/blog/2019/03/07/spring-microservices-https-oauth2) for how to use HTTPS instead.
